version: '3.4'

services:
  image-server:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./config/image-server:/etc/nginx/conf.d
      - ./images:/usr/share/nginx/html/images

  cache-server:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./config/cache-server:/etc/nginx/conf.d
      - ./cache:/var/cache/nginx/images_cache
