version: '3.4'

services:
  image-server:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./images:/usr/share/nginx/html/images
      - ./config/image-server:/etc/nginx/conf.d

  cache-server:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./config/cache-server/nginx.conf:/etc/nginx/nginx.conf
      - ./cache:/usr/share/nginx/cache
